# Default values for all clusters that use this profile
is_prod_cluster: false

hosted_zone: k8s.sugarkube.io            # The domain to host your stuff under.

provisioner:
  params:       # parameters to different kops commands
    global:     # these are applied to all commands
      state: s3://k8s.sugarkube.io      # todo - generate a default value

    create_cluster:       # Parameters for the `kops create cluster` command
      api_loadbalancer_type: public     # More kops settings...
      dns: public
      authorization: RBAC
      networking: calico
      topology: public
      master_count: 1
      master_size: t2.medium
      node_count: 2
      node_size: t2.medium

    rolling_update:
      node_interval: 4m0s

  specs:                              # The kops config will be downloaded and this
    cluster:
      docker:                         # will be patched into the spec before
        logLevel: warn                # applying it to update the cluster config.
        logOpt:                       # This allows kops clusters to be fully
        - max-size=10m                # customised and updated automatically.
        - max-file=5
        logDriver: json-file
        ipMasq: true
        ipTables: true
    instanceGroups:
      nodes:                    # name of the instance group
        nodeLabels:
          kops.k8s.io/test: test-label
        cloudLabels:
          project: test-project-label
        maxSize: 1          # change these then run `sugarkube cluster update -n aws-dev -s examples/stacks.yaml`
        minSize: 1          # and watch the config changes take effect
