# This manifest contains kapps that represent the actual products you're shipping

# Kapps listed under this key will be installed if they are not currently
# installed in the target cluster.
present:

  # This entry demonstrates how to explicitly declare values.
  #
  # Unique identifier. The same kapp can be installed multiple times provided
  # this is unique per instance.
  wordpress-site1:
    name: wordpress               # Defaults to the identifier
    meta:                         # installer-specific values
      namespace: wordpress-sites  # Helm-specific value

    # Sources to checkout as siblings in the cache for this kapp. This allows
    # creating a cache entry from e.g. the actual kapp source, a directory of
    # shared makefiles, and/or pulling in `values.yaml` files etc. from a
    # separately versioned source.
    sources:
    - url: git@github.com:helm/charts.git
      # if this was our repo a good pattern could be to create a signed tag for
      # each release called `<chart>-<version>`.
      branch: master
      path: stable/wordpress/
    - url: git@github.com:sugarkube/sugarkube.git
      branch: master
      # this lets us reuse the same kapp parameterised differently per instance
      path: examples/values/wordpress/site1/
      # Name of the dest dir to write to in the cache. Defaults to the last
      # component of the path which in this case is the same as what we're
      # demonstrating below. But here's how to override it explicitly anyway.
      dest: site1-values
    - url: git@github.com:sugarkube/sample-kapps.git
      branch: master
      path: common-makefiles/
