# kube_context: "{{ cluster }}.{{ region }}.{{ account_name }}.{{ domain }}"    # populated by default but overrideable
kube_context: k8s.sugarkube.io         # todo - default this to the kops cluster name

#s3:
#  kms_key: "arn:..."        # added to generated files to support e.g. encrypted terraform S3 backends.
                             # todo - how to pull this out of the pre-init kapp which should create it?
provisioner:
  params:
    global:
      name: k8s.sugarkube.io

    create_cluster:
      # from https://stable.release.core-os.net/amd64-usr/current/coreos_production_ami_hvm_eu-west-1.txt
      image: ami-099b2d1bdd27b4649

      master-zones: eu-west-1a
      zones: eu-west-1a,eu-west-1b,eu-west-1c
