kapp_sot: helm        # source-of-truth. Works out what's already installed.
installer: make
acquirer: git

# todo - pass these into commands. Probably don't need to be global flags...
minikube_path: minikube
kubectl_path: kubectl